const commonjs = require('rollup-plugin-commonjs');
const babel = require('rollup-plugin-babel');
const license = require('rollup-plugin-license');

let header = `
marked - a markdown parser
Copyright (c) 2011-${new Date().getFullYear()}, Christopher Jeffrey. (MIT Licensed)
https://github.com/markedjs/marked
`;
header = '';
module.exports = {
  input: 'src/editormd.js',
  output: {
    file: 'lib/editor.ict.js',
    format: 'umd',
    name: 'editormd'
  },
  plugins: [
    license({
      banner: `
DO NOT EDIT THIS FILE
The code in this file is generated from files in ./src/
`
    }),
    license({ banner: header}),
    commonjs(),
    babel({
      presets: [['@babel/preset-env', { loose: true }]]
    })
  ]
};
